plugins { id 'com.android.application' }
android {
 namespace 'kr.co.ktmi.companymanager'
 compileSdk 35
 defaultConfig { applicationId 'kr.co.ktmi.companymanager'; minSdk 24; targetSdk 35; versionCode 6; versionName '6.0.0' }
 compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}
dependencies {}
