package kr.co.ktmi.companymanager;
import android.content.*;import org.json.*;import java.util.*;
public final class LocalStore {
 private static android.content.SharedPreferences p(Context c){return c.getSharedPreferences("ktm_app_data",Context.MODE_PRIVATE);}private static JSONArray r(Context c,String k){try{return new JSONArray(p(c).getString(k,"[]"));}catch(Exception e){return new JSONArray();}}private static void w(Context c,String k,JSONArray a){p(c).edit().putString(k,a.toString()).apply();}
 public static List<JSONObject>schedules(Context c){List<JSONObject>o=new ArrayList<>();JSONArray a=r(c,"schedules");for(int i=0;i<a.length();i++)if(a.optJSONObject(i)!=null)o.add(a.optJSONObject(i));Collections.sort(o,Comparator.comparing(x->x.optString("date","")));return o;}
 public static JSONObject saveSchedule(Context c,JSONObject x){JSONArray a=r(c,"schedules");long id=x.optLong("id");if(id==0){id=System.currentTimeMillis();try{x.put("id",id);}catch(Exception ignored){}a.put(x);}else{boolean found=false;for(int i=0;i<a.length();i++)if(a.optJSONObject(i).optLong("id")==id){try{a.put(i,x);}catch(Exception ignored){}found=true;break;}if(!found)a.put(x);}w(c,"schedules",a);return x;}
 public static void deleteSchedule(Context c,long id){JSONArray a=r(c,"schedules"),b=new JSONArray();for(int i=0;i<a.length();i++)if(a.optJSONObject(i).optLong("id")!=id)b.put(a.optJSONObject(i));w(c,"schedules",b);}
 public static List<JSONObject>messages(Context c){List<JSONObject>o=new ArrayList<>();JSONArray a=r(c,"messages");for(int i=a.length()-1;i>=0;i--)o.add(a.optJSONObject(i));return o;}public static void addMessage(Context c,String s){JSONArray a=r(c,"messages");JSONObject o=new JSONObject();try{o.put("id",System.currentTimeMillis());o.put("text",s);o.put("created",new java.text.SimpleDateFormat("yyyy.MM.dd HH:mm",java.util.Locale.KOREA).format(new java.util.Date()));}catch(Exception ignored){}a.put(o);w(c,"messages",a);}public static void deleteMessage(Context c,long id){JSONArray a=r(c,"messages"),b=new JSONArray();for(int i=0;i<a.length();i++)if(a.optJSONObject(i).optLong("id")!=id)b.put(a.optJSONObject(i));w(c,"messages",b);}
 public static boolean notificationsOn(Context c){return p(c).getBoolean("notify",true);}public static boolean vibrationOn(Context c){return p(c).getBoolean("vibrate",true);}public static boolean soundOn(Context c){return p(c).getBoolean("sound",true);}public static int defaultReminderMask(Context c){return p(c).getInt("reminderMask",15);}public static void saveSettings(Context c,boolean n,boolean v,boolean s,int m){p(c).edit().putBoolean("notify",n).putBoolean("vibrate",v).putBoolean("sound",s).putInt("reminderMask",m).apply();}
}
