package kr.co.ktmi.companymanager;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import org.json.*;
import java.text.*;
import java.util.*;

public class MainActivity extends Activity {
 private static final String SITE="https://company-qms-manager.kimyangha.chatgpt.site";
 private static final int NAVY=Color.rgb(8,8,79), BG=Color.rgb(244,246,250), TEAL=Color.rgb(143,193,195);
 private LinearLayout root,content,nav; private TextView title; private WebView web; private ValueCallback<Uri[]> chooser;
 private Calendar month=Calendar.getInstance();
 private int dp(int v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
 private TextView text(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(dp(12),dp(10),dp(12),dp(10));return v;}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(NAVY);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},7);build();ReminderScheduler.rescheduleAll(this);show("schedule".equals(getIntent().getStringExtra("openTab"))?"schedule":"home");}
 private void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(14),dp(8),dp(8),dp(8));h.setBackgroundColor(Color.WHITE);title=text("KTM 업무관리",20,NAVY);title.setTypeface(null,1);h.addView(title,new LinearLayout.LayoutParams(0,dp(54),1));Button gear=new Button(this);gear.setText("⚙");gear.setTextSize(20);gear.setTextColor(NAVY);gear.setBackgroundColor(Color.TRANSPARENT);gear.setOnClickListener(v->showSettings());h.addView(gear,new LinearLayout.LayoutParams(dp(54),dp(54)));root.addView(h);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(12),dp(10),dp(12),dp(10));root.addView(content,new LinearLayout.LayoutParams(-1,0,1));nav=new LinearLayout(this);nav.setBackgroundColor(Color.WHITE);for(String[] n:new String[][]{{"home","⌂\n홈"},{"schedule","▣\n달력"},{"message","✎\n업무메모"},{"system","☰\n관리시스템"}}){Button x=new Button(this);x.setText(n[1]);x.setTextSize(12);x.setTextColor(NAVY);x.setBackgroundColor(Color.TRANSPARENT);x.setOnClickListener(v->show(n[0]));nav.addView(x,new LinearLayout.LayoutParams(0,dp(64),1));}root.addView(nav);setContentView(root);}
 private void clear(String s){title.setText(s);content.removeAllViews();content.setPadding(dp(12),dp(10),dp(12),dp(10));web=null;}
 private LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(12),dp(8),dp(12),dp(8));c.setBackgroundColor(Color.WHITE);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(8));c.setLayoutParams(p);return c;}
 private void show(String t){if(t.equals("schedule"))showSchedule();else if(t.equals("message"))showMessages();else if(t.equals("system"))showSystem();else showHome();}
 private void showHome(){clear("오늘의 업무");ScrollView sc=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);String now=new SimpleDateFormat("yyyy-MM-dd",Locale.KOREA).format(new Date());int today=0,week=0;for(JSONObject o:LocalStore.schedules(this)){if(now.equals(o.optString("date")))today++;if(o.optString("date").compareTo(now)>=0&&!o.optBoolean("done"))week++;}LinearLayout sum=card();TextView hi=text("안녕하세요\n오늘 확인할 일정을 모았습니다.",20,NAVY);hi.setTypeface(null,1);sum.addView(hi);sum.addView(text("오늘 "+today+"건  ·  예정 "+week+"건",15,Color.DKGRAY));box.addView(sum);Button cal=new Button(this);cal.setText("월간 달력 보기");cal.setTextColor(Color.WHITE);cal.setBackgroundColor(NAVY);cal.setOnClickListener(v->showSchedule());box.addView(cal,new LinearLayout.LayoutParams(-1,dp(50)));box.addView(text("다가오는 일정",18,NAVY));int shown=0;for(JSONObject o:LocalStore.schedules(this)){if(o.optString("date").compareTo(now)>=0&&!o.optBoolean("done")&&shown++<6)box.addView(scheduleCard(o));}if(shown==0)box.addView(text("예정된 일정이 없습니다.",15,Color.GRAY));LinearLayout info=card();info.addView(text("알림",17,NAVY));info.addView(text(LocalStore.notificationsOn(this)?"설정한 날짜에 미리 알려드립니다.":"현재 일정 알림이 꺼져 있습니다.",14,Color.DKGRAY));info.setOnClickListener(v->showSettings());box.addView(info);sc.addView(box);content.addView(sc,new LinearLayout.LayoutParams(-1,0,1));}
 private View scheduleCard(JSONObject o){LinearLayout c=card();TextView t=text(o.optString("title"),16,NAVY);t.setTypeface(null,1);c.addView(text(o.optString("date")+(o.optBoolean("done")?"  완료":"  예정"),13,o.optBoolean("done")?Color.GRAY:Color.rgb(55,120,140)));c.addView(t);if(!o.optString("note").isEmpty())c.addView(text(o.optString("note"),13,Color.DKGRAY));c.setOnClickListener(v->editSchedule(o));c.setOnLongClickListener(v->{new AlertDialog.Builder(this).setTitle("일정 삭제").setMessage("삭제할까요?").setNegativeButton("취소",null).setPositiveButton("삭제",(a,b)->{ReminderScheduler.cancel(this,o.optLong("id"));LocalStore.deleteSchedule(this,o.optLong("id"));showSchedule();}).show();return true;});return c;}
 private void showSchedule(){clear("월간 일정");LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER);Button prev=new Button(this);prev.setText("‹");TextView ym=text(new SimpleDateFormat("yyyy년 M월",Locale.KOREA).format(month.getTime()),19,NAVY);ym.setGravity(Gravity.CENTER);ym.setTypeface(null,1);Button next=new Button(this);next.setText("›");prev.setOnClickListener(v->{month.add(Calendar.MONTH,-1);showSchedule();});next.setOnClickListener(v->{month.add(Calendar.MONTH,1);showSchedule();});top.addView(prev,new LinearLayout.LayoutParams(dp(55),dp(48)));top.addView(ym,new LinearLayout.LayoutParams(0,dp(48),1));top.addView(next,new LinearLayout.LayoutParams(dp(55),dp(48)));content.addView(top);GridLayout grid=new GridLayout(this);grid.setColumnCount(7);for(String d:new String[]{"일","월","화","수","목","금","토"}){TextView h=text(d,13,d.equals("일")?Color.RED:d.equals("토")?Color.BLUE:NAVY);h.setGravity(Gravity.CENTER);grid.addView(h,new GridLayout.LayoutParams(GridLayout.spec(GridLayout.UNDEFINED,1,1f),GridLayout.spec(GridLayout.UNDEFINED,1,1f)));}Calendar first=(Calendar)month.clone();first.set(Calendar.DAY_OF_MONTH,1);int blank=first.get(Calendar.DAY_OF_WEEK)-1,max=first.getActualMaximum(Calendar.DAY_OF_MONTH);for(int i=0;i<blank;i++)grid.addView(dayCell("",null,false));String today=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());for(int d=1;d<=max;d++){String ds=String.format(Locale.US,"%04d-%02d-%02d",first.get(Calendar.YEAR),first.get(Calendar.MONTH)+1,d);int count=0;for(JSONObject o:LocalStore.schedules(this))if(ds.equals(o.optString("date")))count++;grid.addView(dayCell(d+(count>0?"\n● "+count:""),ds,ds.equals(today)));}content.addView(grid,new LinearLayout.LayoutParams(-1,0,1));Button add=new Button(this);add.setText("+ 일정 등록");add.setTextColor(Color.WHITE);add.setBackgroundColor(NAVY);add.setOnClickListener(v->editSchedule(null));content.addView(add,new LinearLayout.LayoutParams(-1,dp(52)));}
 private View dayCell(String label,String date,boolean isToday){TextView v=text(label,14,NAVY);v.setGravity(Gravity.TOP|Gravity.CENTER_HORIZONTAL);v.setMinHeight(dp(58));v.setBackgroundColor(isToday?Color.rgb(221,239,240):Color.WHITE);if(date!=null)v.setOnClickListener(x->showDay(date));return v;}
 private void showDay(String date){LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);int n=0;for(JSONObject o:LocalStore.schedules(this))if(date.equals(o.optString("date"))){list.addView(scheduleCard(o));n++;}if(n==0)list.addView(text("등록된 일정이 없습니다.",15,Color.GRAY));new AlertDialog.Builder(this).setTitle(date).setView(list).setNegativeButton("닫기",null).setPositiveButton("새 일정",(a,b)->editScheduleForDate(date)).show();}
 private void editScheduleForDate(String date){try{JSONObject o=new JSONObject();o.put("date",date);editSchedule(o);}catch(Exception ignored){}}
 private void editSchedule(JSONObject old){boolean fresh=old==null||old.optLong("id")==0;LinearLayout f=new LinearLayout(this);f.setOrientation(LinearLayout.VERTICAL);f.setPadding(dp(18),0,dp(18),0);EditText name=new EditText(this);name.setHint("일정명");name.setText(old==null?"":old.optString("title"));f.addView(name);final String[] selected={old==null?"":old.optString("date")};TextView date=text(selected[0].isEmpty()?"날짜 선택":selected[0],16,NAVY);date.setBackgroundColor(Color.rgb(231,242,243));date.setOnClickListener(v->{Calendar n=Calendar.getInstance();new DatePickerDialog(this,(x,y,m,d)->{selected[0]=String.format(Locale.US,"%04d-%02d-%02d",y,m+1,d);date.setText(selected[0]);},n.get(Calendar.YEAR),n.get(Calendar.MONTH),n.get(Calendar.DAY_OF_MONTH)).show();});f.addView(date);EditText note=new EditText(this);note.setHint("메모·준비사항");note.setText(old==null?"":old.optString("note"));f.addView(note);TextView rt=text("이 일정 알림",14,NAVY);f.addView(rt);LinearLayout checks=new LinearLayout(this);int mask=old==null?LocalStore.defaultReminderMask(this):old.optInt("reminderMask",LocalStore.defaultReminderMask(this));CheckBox d14=cb("14일 전",(mask&8)>0),d7=cb("7일 전",(mask&4)>0),d2=cb("2일 전",(mask&2)>0),d1=cb("1일 전",(mask&1)>0);checks.addView(d14);checks.addView(d7);checks.addView(d2);checks.addView(d1);f.addView(checks);CheckBox done=cb("완료된 일정",old!=null&&old.optBoolean("done"));f.addView(done);AlertDialog dlg=new AlertDialog.Builder(this).setTitle(fresh?"새 일정":"일정 수정").setView(f).setNegativeButton("취소",null).setPositiveButton("저장",null).create();dlg.setOnShowListener(x->dlg.getButton(-1).setOnClickListener(v->{if(name.getText().toString().trim().isEmpty()||selected[0].isEmpty()){Toast.makeText(this,"일정명과 날짜를 입력해 주세요.",Toast.LENGTH_SHORT).show();return;}try{JSONObject o=fresh?new JSONObject():new JSONObject(old.toString());o.put("title",name.getText().toString().trim());o.put("date",selected[0]);o.put("note",note.getText().toString().trim());o.put("done",done.isChecked());o.put("reminderMask",(d14.isChecked()?8:0)|(d7.isChecked()?4:0)|(d2.isChecked()?2:0)|(d1.isChecked()?1:0));LocalStore.saveSchedule(this,o);ReminderScheduler.cancel(this,o.optLong("id"));if(!done.isChecked())ReminderScheduler.schedule(this,o);dlg.dismiss();showSchedule();}catch(Exception e){Toast.makeText(this,"저장하지 못했습니다.",Toast.LENGTH_SHORT).show();}}));dlg.show();}
 private CheckBox cb(String s,boolean on){CheckBox c=new CheckBox(this);c.setText(s);c.setChecked(on);return c;}
 private void showSettings(){clear("알림 설정");ScrollView sc=new ScrollView(this);LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);LinearLayout c=card();Switch all=new Switch(this);all.setText("일정 알림 사용");all.setTextSize(17);all.setChecked(LocalStore.notificationsOn(this));c.addView(all);Switch vib=new Switch(this);vib.setText("진동");vib.setChecked(LocalStore.vibrationOn(this));c.addView(vib);Switch sound=new Switch(this);sound.setText("알림음");sound.setChecked(LocalStore.soundOn(this));c.addView(sound);c.addView(text("기본 알림 시점",16,NAVY));CheckBox d14=cb("14일 전",(LocalStore.defaultReminderMask(this)&8)>0),d7=cb("7일 전",(LocalStore.defaultReminderMask(this)&4)>0),d2=cb("2일 전",(LocalStore.defaultReminderMask(this)&2)>0),d1=cb("1일 전",(LocalStore.defaultReminderMask(this)&1)>0);c.addView(d14);c.addView(d7);c.addView(d2);c.addView(d1);b.addView(c);Button save=new Button(this);save.setText("설정 저장");save.setTextColor(Color.WHITE);save.setBackgroundColor(NAVY);save.setOnClickListener(v->{LocalStore.saveSettings(this,all.isChecked(),vib.isChecked(),sound.isChecked(),(d14.isChecked()?8:0)|(d7.isChecked()?4:0)|(d2.isChecked()?2:0)|(d1.isChecked()?1:0));ReminderScheduler.rescheduleAll(this);Toast.makeText(this,"알림 설정을 저장했습니다.",Toast.LENGTH_SHORT).show();showHome();});b.addView(save,new LinearLayout.LayoutParams(-1,dp(52)));LinearLayout sync=card();sync.addView(text("기존 관리시스템 일정 연동",17,NAVY));sync.addView(text("현재 관리시스템은 앱이 일정을 읽을 수 있는 전용 연결 기능이 없어 자동 동기화되지 않습니다. PC 화면을 변경하지 않고 연동하려면 읽기 전용 일정 API가 필요합니다.",14,Color.DKGRAY));b.addView(sync);sc.addView(b);content.addView(sc,new LinearLayout.LayoutParams(-1,0,1));}
 private void showMessages(){clear("업무메모");EditText in=new EditText(this);in.setHint("할 일, 전화내용, 확인사항");in.setMinLines(2);content.addView(in);Button add=new Button(this);add.setText("메모 저장");add.setTextColor(Color.WHITE);add.setBackgroundColor(NAVY);add.setOnClickListener(v->{String s=in.getText().toString().trim();if(!s.isEmpty()){LocalStore.addMessage(this,s);showMessages();}});content.addView(add,new LinearLayout.LayoutParams(-1,dp(50)));ScrollView sc=new ScrollView(this);LinearLayout list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);for(JSONObject o:LocalStore.messages(this)){LinearLayout c=card();c.addView(text(o.optString("text"),16,NAVY));c.addView(text(o.optString("created")+" · 길게 눌러 삭제",12,Color.GRAY));c.setOnLongClickListener(v->{LocalStore.deleteMessage(this,o.optLong("id"));showMessages();return true;});list.addView(c);}sc.addView(list);content.addView(sc,new LinearLayout.LayoutParams(-1,0,1));}
 private void showSystem(){clear("기존 관리시스템");content.setPadding(0,0,0,0);web=new WebView(this);WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(true);s.setAllowContentAccess(true);CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);web.setWebViewClient(new WebViewClient());web.setWebChromeClient(new WebChromeClient(){@Override public boolean onShowFileChooser(WebView w,ValueCallback<Uri[]> cb,FileChooserParams p){chooser=cb;try{startActivityForResult(p.createIntent(),1001);return true;}catch(Exception e){chooser=null;return false;}}});web.setDownloadListener((u,a,c,m,l)->startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u))));web.loadUrl(SITE);content.addView(web,new LinearLayout.LayoutParams(-1,-1));}
 @Override protected void onActivityResult(int r,int x,Intent d){super.onActivityResult(r,x,d);if(r==1001&&chooser!=null){chooser.onReceiveValue(WebChromeClient.FileChooserParams.parseResult(x,d));chooser=null;}}
 @Override public void onBackPressed(){if(web!=null&&web.canGoBack())web.goBack();else super.onBackPressed();}
}
